"use client";

import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Cell, Pie, PieChart, ResponsiveContainer } from "recharts";

const stages = [["Validated", "$48.92M", "w-full bg-blue-700"], ["Recovery Initiated", "$38.15M", "w-[88%] bg-blue-600"], ["Vendor Contacted", "$25.76M", "w-[72%] bg-blue-500"], ["Credit Memo Promised", "$16.42M", "w-[58%] bg-blue-400"], ["Credit Memo Received", "$11.27M", "w-[44%] bg-blue-300"], ["Cash / Offset Applied", "$7.38M", "w-[31%] bg-blue-200"], ["Reconciled", "$5.64M", "w-[20%] bg-slate-200"]];
const aging = [["Validated", [57, 41, 19, 21, 18]], ["Recovery Initiated", [20, 36, 45, 20, 13]], ["Vendor Contacted", [19, 24, 31, 15, 8]], ["Credit Memo Promised", [12, 16, 20, 9, 6]], ["Credit Memo Received", [8, 10, 13, 6, 5]], ["Cash / Offset Applied", [6, 8, 8, 4, 3]], ["Reconciled", [7, 6, 5, 3, 1]]];
const priorities = [{ name: "Critical", value: 18.23, color: "#dc2626" }, { name: "High", value: 17.14, color: "#f97316" }, { name: "Medium", value: 9.85, color: "#fbbf24" }, { name: "Low", value: 3.7, color: "#16a34a" }];
const panel = "rounded-lg border border-slate-200 bg-white p-3 shadow-sm";
const colorForAge = (value) => value >= 40 ? "bg-orange-400 text-white" : value >= 20 ? "bg-orange-200 text-orange-900" : value >= 10 ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800";

export default function RecoveryPipelineOverview() {
  return <section className="grid gap-3 xl:grid-cols-3">
    <article className={panel}><h2 className="text-xs font-semibold text-slate-900">Recovery Pipeline (By Stage)</h2><div className="mt-4 grid grid-cols-[minmax(110px,1fr)_100px] gap-x-3"><div className="space-y-1.5">{stages.map(([label, , width]) => <div key={label} className="flex h-5 justify-center"><span className={`rounded-sm ${width}`} /></div>)}</div><div className="space-y-1.5 text-[9px] leading-5 text-slate-700">{stages.map(([label, amount]) => <div key={label} className="flex justify-between gap-2"><span>{label}</span><span>{amount}</span></div>)}</div></div><div className="mt-3 flex justify-between border-t border-slate-200 pt-3 text-[10px] font-semibold"><span>Conversion Rate</span><span>11.8%</span></div></article>
    <article className={panel}><h2 className="text-xs font-semibold text-slate-900">Recovery Aging (By Stage)</h2><div className="mt-4 grid gap-1 text-center text-[8px]" style={{ gridTemplateColumns: "88px repeat(5, minmax(0, 1fr))" }}><span />{["0-15", "16-30", "31-60", "61-90", "90+"].map((item) => <span key={item} className="font-medium text-slate-500">{item}</span>)}{aging.flatMap(([stage, values]) => [<span key={stage} className="self-center text-left text-[9px] font-medium text-slate-700">{stage}</span>, ...values.map((value, index) => <span key={`${stage}-${index}`} className={`rounded-sm py-1 ${colorForAge(value)}`}>{value}</span>)])}</div><Link href="/reports" className="mt-4 inline-flex items-center gap-1 text-[10px] font-semibold text-blue-600">View full aging report <ArrowRight size={12} /></Link></article>
    <article className={panel}><h2 className="text-xs font-semibold text-slate-900">Recoveries by Priority</h2><div className="mt-4 flex items-center gap-5"><div className="h-32 w-32 shrink-0"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={priorities} dataKey="value" innerRadius={34} outerRadius={53} paddingAngle={2} stroke="none">{priorities.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie></PieChart></ResponsiveContainer></div><div className="space-y-2 text-[10px]">{priorities.map((item) => <div key={item.name} className="flex items-center gap-2"><span className="h-2 w-2 rounded-sm" style={{ backgroundColor: item.color }} /><span className="w-11">{item.name}</span><span>${item.value.toFixed(2)}M ({((item.value / 48.92) * 100).toFixed(1)}%)</span></div>)}</div></div><div className="mt-2 flex justify-between border-t border-slate-200 pt-3 text-[10px] font-semibold"><span>Total</span><span>$48.92M</span></div><Link href="/recoveries" className="mt-3 inline-flex items-center gap-1 text-[10px] font-semibold text-blue-600">View all recoveries <ArrowRight size={12} /></Link></article>
  </section>;
}
