"use client";

import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const events = [
  { day: "May 1", detections: 2100, recommendations: 2900, actions: 1500, overrides: 620 }, { day: "May 6", detections: 4800, recommendations: 3900, actions: 2700, overrides: 900 }, { day: "May 11", detections: 5400, recommendations: 4100, actions: 3100, overrides: 850 }, { day: "May 16", detections: 6100, recommendations: 4600, actions: 3500, overrides: 1200 }, { day: "May 21", detections: 5700, recommendations: 4200, actions: 3000, overrides: 980 }, { day: "May 26", detections: 6800, recommendations: 4900, actions: 3400, overrides: 1060 }, { day: "May 31", detections: 7000, recommendations: 5000, actions: 3600, overrides: 1100 },
];
const types = [{ name: "Detections", value: 6321, color: "#2563eb" }, { name: "AI Recommendations", value: 5842, color: "#6d28d9" }, { name: "User Actions", value: 8036, color: "#16a34a" }, { name: "Overrides", value: 1203, color: "#ef4444" }, { name: "Recovery Events", value: 1114, color: "#f59e0b" }, { name: "System / Others", value: 1189, color: "#64748b" }];
const actors = [{ name: "AI Agent", value: 8733, color: "#2563eb" }, { name: "Users", value: 7875, color: "#6d28d9" }, { name: "System", value: 5232, color: "#14b8a6" }, { name: "Rules Engine", value: 2701, color: "#fbbf24" }];
const risks = [["High Risk", "8,421 (34.3%)", 85, "bg-red-500"], ["Medium Risk", "10,582 (43.1%)", 92, "bg-amber-400"], ["Low Risk", "5,572 (22.7%)", 54, "bg-emerald-500"]];
const panel = "rounded-lg border border-slate-200 bg-white p-4 shadow-sm";

function DonutPanel({ title, data, action }) {
  const total = data.reduce((sum, item) => sum + item.value, 0);
  return <article className={panel}><h2 className="text-xs font-semibold text-slate-900">{title}</h2><div className="mt-4 flex items-center gap-3"><div className="h-32 w-32 shrink-0"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" innerRadius={34} outerRadius={53} paddingAngle={2} stroke="none">{data.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie></PieChart></ResponsiveContainer></div><div className="space-y-2 text-[9px] text-slate-600">{data.map((item) => <div key={item.name} className="flex gap-1.5"><span className="mt-0.5 h-2 w-2 shrink-0 rounded-full" style={{ backgroundColor: item.color }} /><span>{item.name} <b className="text-slate-800">{((item.value / total) * 100).toFixed(1)}% ({item.value.toLocaleString()})</b></span></div>)}</div></div><Link href="/audit" className="mt-4 inline-flex items-center gap-1 text-[11px] font-semibold text-blue-600">{action} <ArrowRight size={13} /></Link></article>;
}

export default function AuditActivityAnalytics() {
  return <section className="mt-4 grid gap-3 xl:grid-cols-4">
    <article className={panel}><h2 className="text-xs font-semibold text-slate-900">Events Over Time</h2><div className="mt-2 flex flex-wrap gap-2 text-[9px] text-slate-600">{[["Detections", "#2563eb"], ["AI Recommendations", "#6d28d9"], ["User Actions", "#16a34a"], ["Overrides", "#ef4444"]].map(([label, color]) => <span key={label}><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full" style={{ backgroundColor: color }} />{label}</span>)}</div><div className="mt-2 h-32"><ResponsiveContainer width="100%" height="100%"><LineChart data={events} margin={{ top: 5, right: 5, left: -25, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="day" tick={{ fontSize: 8, fill: "#64748b" }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 8, fill: "#64748b" }} axisLine={false} tickLine={false} tickFormatter={(value) => `${value / 1000}K`} /><Tooltip /><Line dataKey="detections" stroke="#2563eb" strokeWidth={2} dot={false} /><Line dataKey="recommendations" stroke="#6d28d9" strokeWidth={2} dot={false} /><Line dataKey="actions" stroke="#16a34a" strokeWidth={2} dot={false} /><Line dataKey="overrides" stroke="#ef4444" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div><Link href="/audit" className="mt-4 inline-flex items-center gap-1 text-[11px] font-semibold text-blue-600">View full trend <ArrowRight size={13} /></Link></article>
    <DonutPanel title="Event Type Distribution" data={types} action="View type analysis" />
    <DonutPanel title="Actor Type Distribution" data={actors} action="View actor analysis" />
    <article className={panel}><h2 className="text-xs font-semibold text-slate-900">Risk &amp; Confidence Overview</h2><p className="mt-4 text-[10px] font-semibold text-slate-700">Risk Level (by Events)</p><div className="mt-3 space-y-3">{risks.map(([label, value, score, color]) => <div key={label} className="grid grid-cols-[70px_1fr_76px] items-center gap-2 text-[10px]"><span className="text-slate-600">{label}</span><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{ width: `${score}%` }} /></div><span className="text-right text-slate-600">{value}</span></div>)}</div><div className="mt-5 border-t border-slate-200 pt-4"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2 text-[10px]"><span className="font-semibold text-slate-700">Avg. Confidence</span><span className="font-bold text-slate-800">88.6%</span><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[88.6%] rounded-full bg-emerald-500" /></div></div></div><Link href="/audit" className="mt-4 inline-flex items-center gap-1 text-[11px] font-semibold text-blue-600">View details <ArrowRight size={13} /></Link></article>
  </section>;
}
